<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 ./static/Models/bike/gltf/bike.gltf --transform --types --draco
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Circle: THREE.Mesh
      Circle_1: THREE.Mesh
      Circle002: THREE.Mesh
      Circle002_1: THREE.Mesh
      crankset: THREE.Mesh
      ['chainring-black']: THREE.Mesh
      Circle000: THREE.Mesh
      Circle004_1: THREE.Mesh
      Circle005: THREE.Mesh
      Circle042: THREE.Mesh
      Circle006: THREE.Mesh
      Circle003_2: THREE.Mesh
      Circle010_1: THREE.Mesh
      Circle008_2: THREE.Mesh
      Circle009_2: THREE.Mesh
      Circle011_2: THREE.Mesh
      Circle030_1: THREE.Mesh
      Circle031_1: THREE.Mesh
      Circle032_1: THREE.Mesh
      Circle033_1: THREE.Mesh
      Circle034_1: THREE.Mesh
      Circle035_1: THREE.Mesh
      Circle036_1: THREE.Mesh
      Circle037_1: THREE.Mesh
      Circle038_1: THREE.Mesh
      Circle039_1: THREE.Mesh
      Circle040_1: THREE.Mesh
      Circle041_1: THREE.Mesh
      Circle012: THREE.Mesh
      Circle014_1: THREE.Mesh
      Circle017_1: THREE.Mesh
      Circle015_1: THREE.Mesh
      Circle016_1: THREE.Mesh
      Circle013_1: THREE.Mesh
      Circle018_1: THREE.Mesh
      Circle019_1: THREE.Mesh
      Circle020_1: THREE.Mesh
      Circle021_1: THREE.Mesh
      Circle022_1: THREE.Mesh
      Circle023_1: THREE.Mesh
      Circle024_1: THREE.Mesh
      Circle025_1: THREE.Mesh
      Circle026_1: THREE.Mesh
      Circle027_1: THREE.Mesh
      Circle028_1: THREE.Mesh
      Circle029_1: THREE.Mesh
      Cylinder_4: THREE.Mesh
      ['drivetrain-bolt-1']: THREE.Mesh
      ['drivetrain-bolt-2']: THREE.Mesh
      ['drivetrain-bolt-3']: THREE.Mesh
      ['drivetrain-bolt-4']: THREE.Mesh
      ['drivetrain-bolt-5']: THREE.Mesh
      ['drivetrain-bolt-6']: THREE.Mesh
      ['drivetrain-bolt-7']: THREE.Mesh
      Plane001_1: THREE.Mesh
      washer: THREE.Mesh
      ['front-hub']: THREE.Mesh
      Circle056: THREE.Mesh
      Circle055: THREE.Mesh
      Circle004_2: THREE.Mesh
      Circle005_1: THREE.Mesh
      Circle060: THREE.Mesh
      Circle061: THREE.Mesh
      Circle064: THREE.Mesh
      Circle065: THREE.Mesh
      Circle068: THREE.Mesh
      Circle069: THREE.Mesh
      Circle072: THREE.Mesh
      Circle073: THREE.Mesh
      Circle076: THREE.Mesh
      Circle077: THREE.Mesh
      Circle080: THREE.Mesh
      Circle081: THREE.Mesh
      Circle084: THREE.Mesh
      Circle085: THREE.Mesh
      Circle088: THREE.Mesh
      Circle089: THREE.Mesh
      Circle092: THREE.Mesh
      Circle093: THREE.Mesh
      ['sidewall-front']: THREE.Mesh
      valve001: THREE.Mesh
      ['valve-cap001']: THREE.Mesh
      Circle057: THREE.Mesh
      Circle058: THREE.Mesh
      Circle059: THREE.Mesh
      Circle062: THREE.Mesh
      Circle063: THREE.Mesh
      Circle066: THREE.Mesh
      Circle067: THREE.Mesh
      Circle070: THREE.Mesh
      Circle071: THREE.Mesh
      Circle074: THREE.Mesh
      Circle075: THREE.Mesh
      Circle078: THREE.Mesh
      Circle079: THREE.Mesh
      Circle082: THREE.Mesh
      Circle083: THREE.Mesh
      Circle086: THREE.Mesh
      Circle087: THREE.Mesh
      Circle090: THREE.Mesh
      Circle091: THREE.Mesh
      Circle094: THREE.Mesh
      Cylinder006_1: THREE.Mesh
      Cylinder007_1: THREE.Mesh
      ['lock-nut-4']: THREE.Mesh
      ['lock-nut-3']: THREE.Mesh
      ['axle-nut-8']: THREE.Mesh
      ['axle-nut-7']: THREE.Mesh
      ['axle-nut-5']: THREE.Mesh
      ['axle-nut-6']: THREE.Mesh
      ['front-axle']: THREE.Mesh
      fork: THREE.Mesh
      bullhorn: THREE.Mesh
      ['bar-end-plugs']: THREE.Mesh
      ['stem-bolt-7']: THREE.Mesh
      ['stem-bolt-5']: THREE.Mesh
      ['stem-bolt-6']: THREE.Mesh
      ['stem-bolt-2']: THREE.Mesh
      ['stem-bolt-4']: THREE.Mesh
      ['stem-bolt-3']: THREE.Mesh
      ['stem-bolt-1']: THREE.Mesh
      ['stem-cap']: THREE.Mesh
      stem: THREE.Mesh
      spacers: THREE.Mesh
      Helix003: THREE.Mesh
      cog: THREE.Mesh
      Circle002_3: THREE.Mesh
      ['rear-hub']: THREE.Mesh
      Circle_3: THREE.Mesh
      Circle003: THREE.Mesh
      Circle006_1: THREE.Mesh
      Circle010: THREE.Mesh
      Circle033: THREE.Mesh
      Circle034: THREE.Mesh
      Circle035: THREE.Mesh
      Circle036: THREE.Mesh
      Circle037: THREE.Mesh
      Circle038: THREE.Mesh
      Circle039: THREE.Mesh
      Circle040: THREE.Mesh
      Circle041: THREE.Mesh
      Circle042_1: THREE.Mesh
      Circle043: THREE.Mesh
      Circle044: THREE.Mesh
      Circle045: THREE.Mesh
      Circle046: THREE.Mesh
      Circle047: THREE.Mesh
      Circle048: THREE.Mesh
      Circle049: THREE.Mesh
      Circle050: THREE.Mesh
      Circle051: THREE.Mesh
      Circle052: THREE.Mesh
      Circle053: THREE.Mesh
      Circle054: THREE.Mesh
      Circle008: THREE.Mesh
      Circle009_1: THREE.Mesh
      Circle011: THREE.Mesh
      Circle012_1: THREE.Mesh
      Circle013: THREE.Mesh
      Circle014: THREE.Mesh
      Circle027: THREE.Mesh
      Circle028: THREE.Mesh
      Circle029: THREE.Mesh
      Circle030: THREE.Mesh
      Circle031: THREE.Mesh
      Circle032: THREE.Mesh
      Circle015: THREE.Mesh
      Circle016: THREE.Mesh
      Circle017: THREE.Mesh
      Circle018: THREE.Mesh
      Circle019: THREE.Mesh
      Circle020: THREE.Mesh
      Circle021: THREE.Mesh
      Circle022: THREE.Mesh
      Circle023: THREE.Mesh
      Circle024: THREE.Mesh
      Circle025: THREE.Mesh
      Circle026: THREE.Mesh
      Cylinder003: THREE.Mesh
      Cylinder004: THREE.Mesh
      Helix: THREE.Mesh
      ['sidewall-rear']: THREE.Mesh
      valve: THREE.Mesh
      ['valve-cap']: THREE.Mesh
      collar: THREE.Mesh
      ['lock-nut-2']: THREE.Mesh
      ['lock-nut']: THREE.Mesh
      ['axle-nut-4']: THREE.Mesh
      ['axle-nut-3']: THREE.Mesh
      ['axle-nut-2']: THREE.Mesh
      ['axle-nut']: THREE.Mesh
      ['rear-axle']: THREE.Mesh
      ['seat-post-clamp']: THREE.Mesh
      ['seat-post-clamp-bolt']: THREE.Mesh
      ['seat-post-clamp-nut']: THREE.Mesh
      ['bottle-cage-nut-4']: THREE.Mesh
      ['bottle-cage-nut-3']: THREE.Mesh
      ['bottle-cage-nut-2']: THREE.Mesh
      ['bottle-cage-nut-1']: THREE.Mesh
      headset: THREE.Mesh
      frame: THREE.Mesh
      ['saddle-clamp-bolt-glossy']: THREE.Mesh
      ['saddle-clamp-bolt']: THREE.Mesh
      ['saddle-velo-vl-1311']: THREE.Mesh
      ['seat-clamp']: THREE.Mesh
      ['seat-post']: THREE.Mesh
      ['saddle-rails']: THREE.Mesh
      ['saddle-black-plastic']: THREE.Mesh
    }
    materials: {
      ['chain-inner-links']: THREE.MeshStandardMaterial
      ['chain-pins']: THREE.MeshStandardMaterial
      ['chainrnig-black']: THREE.MeshStandardMaterial
      ['pedal-axle']: THREE.MeshStandardMaterial
      ['reflector-orange-plastic']: THREE.MeshStandardMaterial
      ['pedal-reflector']: THREE.MeshStandardMaterial
      ['pedal-spikes']: THREE.MeshStandardMaterial
      ['crankset-bolts']: THREE.MeshStandardMaterial
      ['chainring-bolts']: THREE.MeshStandardMaterial
      washer: THREE.MeshStandardMaterial
      ['grand-bois-tire']: THREE.MeshStandardMaterial
      spoke: THREE.MeshStandardMaterial
      valve: THREE.MeshStandardMaterial
      ['valve-cap']: THREE.MeshStandardMaterial
      ['hub-bearing']: THREE.MeshStandardMaterial
      ['hub-inner-ring']: THREE.MeshStandardMaterial
      ['lock-nut']: THREE.MeshStandardMaterial
      ['axle-nuts']: THREE.MeshStandardMaterial
      axles: THREE.MeshStandardMaterial
      ['wabi-frame-carpaint']: THREE.MeshStandardMaterial
      bullhorn: THREE.MeshStandardMaterial
      ['stem-bolts']: THREE.MeshStandardMaterial
      ['stem-cap']: THREE.MeshStandardMaterial
      stem: THREE.MeshStandardMaterial
      bartape: THREE.MeshStandardMaterial
      ['cog-lockring']: THREE.MeshStandardMaterial
      ['bb-collar']: THREE.MeshStandardMaterial
      ['seat-post-clamp-bolt']: THREE.MeshStandardMaterial
      ['seat-post-clamp-nut']: THREE.MeshStandardMaterial
      headset: THREE.MeshStandardMaterial
      ['saddle-clamp-bolt-glossy']: THREE.MeshStandardMaterial
      ['saddle-clamp-bolt']: THREE.MeshStandardMaterial
      ['seat-clamp']: THREE.MeshStandardMaterial
      ['seat-post']: THREE.MeshStandardMaterial
      ['saddle-rails']: THREE.MeshStandardMaterial
      ['saddle-black-plastic']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/bike-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group position={[0, 0.34, 0]}>
      <T.Group position={[-0.5, 0, 0.35]}>
        <T.Group position={[0.54, 0, -0.01]}>
          <T.Mesh
            geometry={gltf.nodes.Circle.geometry}
            material={gltf.materials['chain-inner-links']}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle_1.geometry}
            material={gltf.materials['chain-pins']}
          />
        </T.Group>
        <T.Group position={[0.54, 0, 0]}>
          <T.Mesh
            geometry={gltf.nodes.Circle002.geometry}
            material={gltf.materials['chain-inner-links']}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle002_1.geometry}
            material={gltf.materials['chain-pins']}
          />
        </T.Group>
      </T.Group>
      <T.Group
        position={[0, -0.06, 0.1]}
        rotation={[-2.68, 0, 0]}
      >
        <T.Group position={[0, 0.06, 0.4]}>
          <T.Mesh
            geometry={gltf.nodes.crankset.geometry}
            material={gltf.materials['chainrnig-black']}
            position={[0.04, -0.06, -0.4]}
            rotation={[-0.05, 0, 0]}
          >
            <T.Mesh
              geometry={gltf.nodes['chainring-black'].geometry}
              material={gltf.materials['chainrnig-black']}
            />
            <T.Mesh
              geometry={gltf.nodes.Circle000.geometry}
              material={gltf.materials['chain-inner-links']}
            />
            <T.Mesh
              geometry={gltf.nodes.Circle004_1.geometry}
              material={gltf.materials['chain-inner-links']}
            />
            <T.Mesh
              geometry={gltf.nodes.Circle005.geometry}
              material={gltf.materials['pedal-axle']}
              position={[0.02, 0, -0.17]}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes.Circle042.geometry}
              material={gltf.materials['pedal-axle']}
              position={[-0.1, 0, 0.17]}
              rotation={[3.1, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes.Circle006.geometry}
              material={gltf.materials['chainrnig-black']}
              position={[0.1, 0, -0.17]}
            >
              <T.Mesh
                geometry={gltf.nodes.Circle003_2.geometry}
                material={gltf.materials['reflector-orange-plastic']}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle010_1.geometry}
                material={gltf.materials['reflector-orange-plastic']}
                rotation={[0, 0, -Math.PI]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle008_2.geometry}
                material={gltf.materials['pedal-reflector']}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle009_2.geometry}
                material={gltf.materials['pedal-reflector']}
                rotation={[0, 0, -Math.PI]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle011_2.geometry}
                material={gltf.materials['chain-inner-links']}
                position={[0.05, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle030_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, -0.04]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle031_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, -0.01, -0.04]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle032_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, -0.01]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle033_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, 0.01]}
                rotation={[0, 0, Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle034_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, -0.01, 0.04]}
                rotation={[0, 0, Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle035_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, 0.04]}
                rotation={[0, 0, Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle036_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, 0.04]}
                rotation={[Math.PI, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle037_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, 0.01, 0.04]}
                rotation={[Math.PI, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle038_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, 0.01]}
                rotation={[Math.PI, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle039_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, -0.01]}
                rotation={[Math.PI, 0, Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle040_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, 0.01, -0.04]}
                rotation={[Math.PI, 0, Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle041_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, -0.04]}
                rotation={[Math.PI, 0, Math.PI]}
              />
            </T.Mesh>
            <T.Mesh
              geometry={gltf.nodes.Circle012.geometry}
              material={gltf.materials['chainrnig-black']}
              position={[-0.19, 0, 0.17]}
              rotation={[2.65, 0, Math.PI]}
            >
              <T.Mesh
                geometry={gltf.nodes.Circle014_1.geometry}
                material={gltf.materials['reflector-orange-plastic']}
                rotation={[0, 0, -Math.PI]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle017_1.geometry}
                material={gltf.materials['reflector-orange-plastic']}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle015_1.geometry}
                material={gltf.materials['pedal-reflector']}
                rotation={[0, 0, -Math.PI]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle016_1.geometry}
                material={gltf.materials['pedal-reflector']}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle013_1.geometry}
                material={gltf.materials['chain-inner-links']}
                position={[0.05, 0, 0]}
                rotation={[-1.19, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle018_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, -0.04]}
                rotation={[-Math.PI, 0, -Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle019_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, 0.01, -0.04]}
                rotation={[-Math.PI, 0, -Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle020_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, -0.01]}
                rotation={[-Math.PI, 0, -Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle021_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, 0.01]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle022_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, 0.01, 0.04]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle023_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, 0.01, 0.04]}
                rotation={[-Math.PI, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle024_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, 0.04]}
                rotation={[0, 0, -Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle025_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, -0.01, 0.04]}
                rotation={[0, 0, -Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle026_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, 0.01]}
                rotation={[0, 0, -Math.PI]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle027_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, -0.01]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle028_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[-0.03, -0.01, -0.04]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle029_1.geometry}
                material={gltf.materials['pedal-spikes']}
                position={[0.04, -0.01, -0.04]}
                scale={-1}
              />
            </T.Mesh>
            <T.Mesh
              geometry={gltf.nodes.Cylinder_4.geometry}
              material={gltf.materials['chain-inner-links']}
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-1'].geometry}
              material={gltf.materials['crankset-bolts']}
              position={[0.02, 0, 0]}
              rotation={[0.73, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-2'].geometry}
              material={gltf.materials['crankset-bolts']}
              position={[-0.1, 0, 0]}
              rotation={[0.49, 0, -Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-3'].geometry}
              material={gltf.materials['chainring-bolts']}
              position={[0, 0, 0.07]}
              rotation={[0.54, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-4'].geometry}
              material={gltf.materials['chainring-bolts']}
              position={[0, -0.07, 0.02]}
              rotation={[1.79, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-5'].geometry}
              material={gltf.materials['chainring-bolts']}
              position={[0, -0.04, -0.06]}
              rotation={[3.05, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-6'].geometry}
              material={gltf.materials['chainring-bolts']}
              position={[0, 0.04, -0.06]}
              rotation={[-1.98, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes['drivetrain-bolt-7'].geometry}
              material={gltf.materials['chainring-bolts']}
              position={[0, 0.07, 0.02]}
              rotation={[-0.72, 0, Math.PI / 2]}
            />
            <T.Mesh
              geometry={gltf.nodes.Plane001_1.geometry}
              material={gltf.materials['chainrnig-black']}
              position={[-0.08, 0, 0]}
              rotation={[Math.PI, 0, Math.PI]}
            />
            <T.Mesh
              geometry={gltf.nodes.washer.geometry}
              material={gltf.materials.washer}
              position={[-0.04, 0, 0]}
              rotation={[1.76, 0, Math.PI / 2]}
            />
          </T.Mesh>
        </T.Group>
      </T.Group>
      <T.Group
        position={[0, 0.43, -0.3]}
        rotation={[0.3, 0, 0]}
      >
        <T.Group
          position={[0, -0.46, -0.04]}
          rotation={[-0.3, 0, 0]}
        >
          <T.Group position={[0, 0, 0.98]}>
            <T.Mesh
              geometry={gltf.nodes['front-hub'].geometry}
              material={gltf.materials['pedal-reflector']}
              position={[0, 0, -0.98]}
            >
              <T.Mesh
                geometry={gltf.nodes.Circle056.geometry}
                material={gltf.materials['chain-inner-links']}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle055.geometry}
                material={gltf.materials['grand-bois-tire']}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle004_2.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.24, 0.17]}
                rotation={[2.23, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle005_1.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.29, 0]}
                rotation={[1.6, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle060.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.09, 0.28]}
                rotation={[2.86, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle061.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.09, 0.28]}
                rotation={[-2.8, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle064.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.24, 0.17]}
                rotation={[-2.17, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle065.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.3, 0]}
                rotation={[-1.54, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle068.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.24, -0.17]}
                rotation={[-0.91, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle069.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.09, -0.28]}
                rotation={[-0.28, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle072.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.09, -0.28]}
                rotation={[0.34, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle073.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.24, -0.17]}
                rotation={[0.97, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle076.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.28, -0.09]}
                rotation={[-1.86, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle077.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.17, -0.24]}
                rotation={[-2.48, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle080.geometry}
                material={gltf.materials.spoke}
                position={[0, 0, -0.3]}
                rotation={[-3.11, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle081.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.17, -0.24]}
                rotation={[2.54, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle084.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.28, -0.09]}
                rotation={[1.91, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle085.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.28, 0.09]}
                rotation={[1.29, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle088.geometry}
                material={gltf.materials.spoke}
                position={[0, -0.17, 0.24]}
                rotation={[0.66, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle089.geometry}
                material={gltf.materials.spoke}
                position={[0, 0, 0.3]}
                rotation={[0.03, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle092.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.17, 0.24]}
                rotation={[-0.6, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle093.geometry}
                material={gltf.materials.spoke}
                position={[0, 0.28, 0.09]}
                rotation={[-1.23, 0, -Math.PI / 2]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes['sidewall-front'].geometry}
                material={gltf.materials['chain-inner-links']}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              />
              <T.Mesh
                geometry={gltf.nodes.valve001.geometry}
                material={gltf.materials.valve}
                position={[0, 0.13, -0.26]}
                rotation={[2.04, 0, 0]}
              >
                <T.Mesh
                  geometry={gltf.nodes['valve-cap001'].geometry}
                  material={gltf.materials['valve-cap']}
                  position={[0, 0.02, 0]}
                />
              </T.Mesh>
              <T.Mesh
                geometry={gltf.nodes.Circle057.geometry}
                material={gltf.materials.spoke}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle058.geometry}
                material={gltf.materials.spoke}
                rotation={[Math.PI / 5, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle059.geometry}
                material={gltf.materials.spoke}
                rotation={[1.26, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle062.geometry}
                material={gltf.materials.spoke}
                rotation={[1.88, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle063.geometry}
                material={gltf.materials.spoke}
                rotation={[2.51, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle066.geometry}
                material={gltf.materials.spoke}
                rotation={[-Math.PI, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle067.geometry}
                material={gltf.materials.spoke}
                rotation={[-2.51, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle070.geometry}
                material={gltf.materials.spoke}
                rotation={[-1.88, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle071.geometry}
                material={gltf.materials.spoke}
                rotation={[-1.26, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle074.geometry}
                material={gltf.materials.spoke}
                rotation={[-Math.PI / 5, 0, 0]}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle075.geometry}
                material={gltf.materials.spoke}
                rotation={[2.83, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle078.geometry}
                material={gltf.materials.spoke}
                rotation={[2.2, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle079.geometry}
                material={gltf.materials.spoke}
                rotation={[Math.PI / 2, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle082.geometry}
                material={gltf.materials.spoke}
                rotation={[0.94, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle083.geometry}
                material={gltf.materials.spoke}
                rotation={[Math.PI / 10, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle086.geometry}
                material={gltf.materials.spoke}
                rotation={[-Math.PI / 10, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle087.geometry}
                material={gltf.materials.spoke}
                rotation={[-0.94, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle090.geometry}
                material={gltf.materials.spoke}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle091.geometry}
                material={gltf.materials.spoke}
                rotation={[-2.2, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Circle094.geometry}
                material={gltf.materials.spoke}
                rotation={[-2.83, 0, 0]}
                scale={-1}
              />
              <T.Mesh
                geometry={gltf.nodes.Cylinder006_1.geometry}
                material={gltf.materials['hub-bearing']}
              />
              <T.Mesh
                geometry={gltf.nodes.Cylinder007_1.geometry}
                material={gltf.materials['hub-inner-ring']}
              />
            </T.Mesh>
          </T.Group>
        </T.Group>
        <T.Group
          position={[0, -0.17, 0.89]}
          rotation={[-0.3, 0, 0]}
        >
          <T.Mesh
            geometry={gltf.nodes['lock-nut-4'].geometry}
            material={gltf.materials['lock-nut']}
            position={[-0.05, 0, -0.98]}
            rotation={[2.66, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes['lock-nut-3'].geometry}
            material={gltf.materials['lock-nut']}
            position={[0.05, 0, -0.98]}
            rotation={[1.21, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['axle-nut-8'].geometry}
            material={gltf.materials['axle-nuts']}
            position={[-0.03, 0, -0.98]}
            rotation={[-3.08, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes['axle-nut-7'].geometry}
            material={gltf.materials['axle-nuts']}
            position={[-0.05, 0, -0.98]}
            rotation={[0.68, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes['axle-nut-5'].geometry}
            material={gltf.materials['axle-nuts']}
            position={[0.05, 0, -0.98]}
            rotation={[1.88, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['axle-nut-6'].geometry}
            material={gltf.materials['axle-nuts']}
            position={[0.03, 0, -0.98]}
            rotation={[1.13, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['front-axle'].geometry}
            material={gltf.materials.axles}
            position={[0, 0, -0.98]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.fork.geometry}
            material={gltf.materials['wabi-frame-carpaint']}
            position={[0, 0.34, -0.83]}
            rotation={[0.3, 0, 0]}
          />
        </T.Group>
        <T.Group
          position={[0, -0.17, 0.89]}
          rotation={[-0.3, 0, 0]}
        >
          <T.Mesh
            geometry={gltf.nodes.bullhorn.geometry}
            material={gltf.materials.bullhorn}
            position={[0, 0.58, -0.87]}
          />
          <T.Mesh
            geometry={gltf.nodes['bar-end-plugs'].geometry}
            material={gltf.materials['chain-inner-links']}
            position={[0, 0.58, -0.87]}
            rotation={[-0.96, 0, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-7'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[0, 0.59, -0.75]}
            rotation={[-2.84, 0, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-5'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[-0.01, 0.58, -0.74]}
            rotation={[-1.27, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-6'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[0.01, 0.56, -0.75]}
            rotation={[1.87, 0, Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-2'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[-0.02, 0.59, -0.88]}
            rotation={[-Math.PI / 2, 0.62, -Math.PI]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-4'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[-0.02, 0.56, -0.88]}
            rotation={[-Math.PI / 2, -0.88, Math.PI]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-3'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[0.02, 0.56, -0.88]}
            rotation={[Math.PI / 2, -0.71, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-bolt-1'].geometry}
            material={gltf.materials['stem-bolts']}
            position={[0.02, 0.59, -0.88]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes['stem-cap'].geometry}
            material={gltf.materials['stem-cap']}
            position={[0, 0.59, -0.75]}
            rotation={[0.3, 0, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes.stem.geometry}
            material={gltf.materials.stem}
            position={[0, 0.58, -0.9]}
          />
          <T.Mesh
            geometry={gltf.nodes.spacers.geometry}
            material={gltf.materials['chain-inner-links']}
            position={[0, 0.51, -0.78]}
            rotation={[0.3, 0, 0]}
          />
          <T.Mesh
            geometry={gltf.nodes.Helix003.geometry}
            material={gltf.materials.bartape}
            position={[0, 0.58, -0.87]}
          />
        </T.Group>
      </T.Group>
      <T.Group
        position={[0, 0, 0.5]}
        rotation={[-1.79, 0, 0]}
      >
        <T.Mesh
          geometry={gltf.nodes.cog.geometry}
          material={gltf.materials['stem-cap']}
          position={[0.03, 0, 0]}
          rotation={[0.26, 0, 0]}
        >
          <T.Mesh
            geometry={gltf.nodes.Circle002_3.geometry}
            material={gltf.materials['cog-lockring']}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
        </T.Mesh>
        <T.Mesh
          geometry={gltf.nodes['rear-hub'].geometry}
          material={gltf.materials['pedal-reflector']}
        >
          <T.Mesh
            geometry={gltf.nodes.Circle_3.geometry}
            material={gltf.materials['chain-inner-links']}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle003.geometry}
            material={gltf.materials['grand-bois-tire']}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle006_1.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.29, 0]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle010.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.15, 0.26]}
            rotation={[2.62, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle033.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.15, 0.26]}
            rotation={[-2.62, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle034.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.29, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle035.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.15, -0.26]}
            rotation={[-Math.PI / 6, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle036.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.15, -0.26]}
            rotation={[Math.PI / 6, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle037.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.26, -0.15]}
            rotation={[1.11, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle038.geometry}
            material={gltf.materials.spoke}
            position={[0, 0, -0.29]}
            rotation={[0.07, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle039.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.26, -0.15]}
            rotation={[-0.98, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle040.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.26, 0.15]}
            rotation={[-2.03, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle041.geometry}
            material={gltf.materials.spoke}
            position={[0, 0, 0.3]}
            rotation={[-3.08, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle042_1.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.26, 0.15]}
            rotation={[2.16, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle043.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.21, 0.21]}
            rotation={[-0.72, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle044.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.08, 0.28]}
            rotation={[0.33, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle045.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.28, 0.08]}
            rotation={[1.37, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle046.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.21, -0.21]}
            rotation={[2.42, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle047.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.08, -0.28]}
            rotation={[-2.81, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle048.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.28, -0.08]}
            rotation={[-1.77, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle049.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.21, -0.21]}
            rotation={[-2.36, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle050.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.08, -0.28]}
            rotation={[2.88, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle051.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.28, -0.08]}
            rotation={[1.83, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle052.geometry}
            material={gltf.materials.spoke}
            position={[0, -0.21, 0.21]}
            rotation={[Math.PI / 4, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle053.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.08, 0.28]}
            rotation={[-0.26, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle054.geometry}
            material={gltf.materials.spoke}
            position={[0, 0.28, 0.08]}
            rotation={[-1.31, 0.09, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle008.geometry}
            material={gltf.materials.spoke}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle009_1.geometry}
            material={gltf.materials.spoke}
            rotation={[2.62, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle011.geometry}
            material={gltf.materials.spoke}
            rotation={[-2.62, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle012_1.geometry}
            material={gltf.materials.spoke}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle013.geometry}
            material={gltf.materials.spoke}
            rotation={[-Math.PI / 6, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle014.geometry}
            material={gltf.materials.spoke}
            rotation={[Math.PI / 6, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle027.geometry}
            material={gltf.materials.spoke}
            rotation={[-2.36, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle028.geometry}
            material={gltf.materials.spoke}
            rotation={[2.88, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle029.geometry}
            material={gltf.materials.spoke}
            rotation={[1.83, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle030.geometry}
            material={gltf.materials.spoke}
            rotation={[Math.PI / 4, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle031.geometry}
            material={gltf.materials.spoke}
            rotation={[-0.26, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle032.geometry}
            material={gltf.materials.spoke}
            rotation={[-1.31, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle015.geometry}
            material={gltf.materials.spoke}
            rotation={[2.09, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle016.geometry}
            material={gltf.materials.spoke}
            rotation={[Math.PI, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle017.geometry}
            material={gltf.materials.spoke}
            rotation={[-2.09, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle018.geometry}
            material={gltf.materials.spoke}
            rotation={[-Math.PI / 3, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle019.geometry}
            material={gltf.materials.spoke}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle020.geometry}
            material={gltf.materials.spoke}
            rotation={[Math.PI / 3, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle021.geometry}
            material={gltf.materials.spoke}
            rotation={[-1.83, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle022.geometry}
            material={gltf.materials.spoke}
            rotation={[-2.88, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle023.geometry}
            material={gltf.materials.spoke}
            rotation={[2.36, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle024.geometry}
            material={gltf.materials.spoke}
            rotation={[1.31, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle025.geometry}
            material={gltf.materials.spoke}
            rotation={[0.26, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Circle026.geometry}
            material={gltf.materials.spoke}
            rotation={[-Math.PI / 4, 0, -Math.PI / 2]}
            scale={-1}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder003.geometry}
            material={gltf.materials['hub-inner-ring']}
          />
          <T.Mesh
            geometry={gltf.nodes.Cylinder004.geometry}
            material={gltf.materials['hub-bearing']}
          />
          <T.Mesh
            geometry={gltf.nodes.Helix.geometry}
            material={gltf.materials['pedal-reflector']}
            position={[-0.05, 0, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes['sidewall-rear'].geometry}
            material={gltf.materials['chain-inner-links']}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <T.Mesh
            geometry={gltf.nodes.valve.geometry}
            material={gltf.materials.valve}
            position={[0, -0.29, 0.04]}
            rotation={[-0.13, 0, 0]}
          >
            <T.Mesh
              geometry={gltf.nodes['valve-cap'].geometry}
              material={gltf.materials['valve-cap']}
              position={[0, 0.02, 0]}
            />
          </T.Mesh>
        </T.Mesh>
      </T.Group>
      <T.Group position={[0, 0, 0.5]}>
        <T.Mesh
          geometry={gltf.nodes.collar.geometry}
          material={gltf.materials['bb-collar']}
          position={[0, 0.46, -0.24]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['lock-nut-2'].geometry}
          material={gltf.materials['lock-nut']}
          position={[-0.06, 0, 0]}
          rotation={[-2.56, 0, -Math.PI / 2]}
          scale={-1}
        />
        <T.Mesh
          geometry={gltf.nodes['lock-nut'].geometry}
          material={gltf.materials['lock-nut']}
          position={[0.06, 0, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <T.Mesh
          geometry={gltf.nodes['axle-nut-4'].geometry}
          material={gltf.materials['axle-nuts']}
          position={[-0.04, 0, 0]}
          rotation={[-0.45, 0, -Math.PI / 2]}
          scale={-1}
        />
        <T.Mesh
          geometry={gltf.nodes['axle-nut-3'].geometry}
          material={gltf.materials['axle-nuts']}
          position={[0.04, 0, 0]}
          rotation={[2.11, 0, -Math.PI / 2]}
        />
        <T.Mesh
          geometry={gltf.nodes['axle-nut-2'].geometry}
          material={gltf.materials['axle-nuts']}
          position={[-0.07, 0, 0]}
          rotation={[-0.93, 0, -Math.PI / 2]}
          scale={-1}
        />
        <T.Mesh
          geometry={gltf.nodes['axle-nut'].geometry}
          material={gltf.materials['axle-nuts']}
          position={[0.07, 0, 0]}
          rotation={[2.45, 0, -Math.PI / 2]}
        />
        <T.Mesh
          geometry={gltf.nodes['rear-axle'].geometry}
          material={gltf.materials.axles}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        />
        <T.Mesh
          geometry={gltf.nodes['seat-post-clamp'].geometry}
          material={gltf.materials['chain-inner-links']}
          position={[0, 0.49, -0.23]}
          rotation={[0.3, 0, 0]}
        >
          <T.Mesh
            geometry={gltf.nodes['seat-post-clamp-bolt'].geometry}
            material={gltf.materials['seat-post-clamp-bolt']}
          />
          <T.Mesh
            geometry={gltf.nodes['seat-post-clamp-nut'].geometry}
            material={gltf.materials['seat-post-clamp-nut']}
          />
        </T.Mesh>
        <T.Mesh
          geometry={gltf.nodes['bottle-cage-nut-4'].geometry}
          material={gltf.materials['chain-inner-links']}
          position={[0, 0.15, -0.57]}
          rotation={[0.83, -1.11, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['bottle-cage-nut-3'].geometry}
          material={gltf.materials['chain-inner-links']}
          position={[0, 0.11, -0.53]}
          rotation={[0.83, 0.83, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['bottle-cage-nut-2'].geometry}
          material={gltf.materials['chain-inner-links']}
          position={[0, 0.12, -0.37]}
          rotation={[-1.27, -0.7, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['bottle-cage-nut-1'].geometry}
          material={gltf.materials['chain-inner-links']}
          position={[0, 0.18, -0.35]}
          rotation={[-1.27, -0.19, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.headset.geometry}
          material={gltf.materials.headset}
          position={[0, 0.49, -0.78]}
          rotation={[0.3, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes.frame.geometry}
          material={gltf.materials['stem-cap']}
          position={[0, 0.46, -0.24]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </T.Group>
      <T.Group position={[0, 0, 0.5]}>
        <T.Mesh
          geometry={gltf.nodes['saddle-clamp-bolt-glossy'].geometry}
          material={gltf.materials['saddle-clamp-bolt-glossy']}
          position={[0, 0.58, -0.18]}
          rotation={[0.12, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['saddle-clamp-bolt'].geometry}
          material={gltf.materials['saddle-clamp-bolt']}
          position={[0, 0.58, -0.18]}
          rotation={[0.12, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['saddle-velo-vl-1311'].geometry}
          material={gltf.materials.bartape}
          position={[0, 0.66, -0.12]}
          rotation={[-0.06, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['seat-clamp'].geometry}
          material={gltf.materials['seat-clamp']}
          position={[0, 0.61, -0.17]}
          rotation={[0.13, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['seat-post'].geometry}
          material={gltf.materials['seat-post']}
          position={[0, 0.48, -0.24]}
          rotation={[0.3, 0, 0]}
        />
        <T.Mesh
          geometry={gltf.nodes['saddle-rails'].geometry}
          material={gltf.materials['saddle-rails']}
          position={[0, 0.59, -0.19]}
        />
        <T.Mesh
          geometry={gltf.nodes['saddle-black-plastic'].geometry}
          material={gltf.materials['saddle-black-plastic']}
          position={[0, 0.65, -0.18]}
          rotation={[0.02, 0, 0]}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
