<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/mercian-models/lugged4.glb -s
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('/static/mercian-models/lugged4.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[0.09, 0.57, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
			<T.Group position={[14.65, 0.37, 15.04]}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Tube.geometry}
					material={gltf.nodes.Tube.material}
					position={[39.19, 3.04, 3.64]}
					rotation={[Math.PI / 2, 0, 0]}
				/>
				<T.Group position={[-25.36, -0.37, 28.15]} rotation={[-0.01, 0, 0]}>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Cube_2.geometry}
						material={gltf.nodes.Cube_2.material}
						position={[50.59, -1.64, -56.41]}
						rotation={[0, 0.32, 0]}
					/>
				</T.Group>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube_1_2.geometry}
					material={gltf.nodes.Cube_1_2.material}
					position={[25.36, 0.37, -28.15]}
					rotation={[0, 0.23, 0]}
				/>
				<T.Group position={[-25.36, 0.37, 28.15]} rotation={[-0.01, 0, 0]}>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Cube.geometry}
						material={gltf.nodes.Cube.material}
						position={[50.59, 3.28, -56.34]}
						rotation={[0, 0.32, 0]}
					/>
				</T.Group>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube_1.geometry}
					material={gltf.nodes.Cube_1.material}
					position={[25.36, -0.37, -28.15]}
					rotation={[0, 0.23, 0]}
				/>
			</T.Group>
			<T.Group position={[35.83, 1.91, -18.97]}>
				<T.Group position={[-40.24, -1.92, 42.72]}>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Lug_1.geometry}
						material={gltf.nodes.Lug_1.material}
						position={[2.57, 0.01, 0.14]}
						rotation={[0, -0.76, 0]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Lug_1_1.geometry}
						material={gltf.nodes.Lug_1_1.material}
						position={[1.52, 0.01, -0.21]}
						rotation={[0, 0.31, 0]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Lug_1_2.geometry}
						material={gltf.nodes.Lug_1_2.material}
						position={[-13.19, 0.01, -46.66]}
						rotation={[Math.PI, -0.31, Math.PI]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Lug_1_3.geometry}
						material={gltf.nodes.Lug_1_3.material}
						position={[-12.92, 0.01, -48.2]}
						rotation={[0, -1.57, 0]}
					/>
				</T.Group>
				<T.Group position={[-3.42, 3.83, -7.03]}>
					<T.Group position={[-41.6, -5.74, 69.52]}>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.Extrude001.geometry}
							material={gltf.nodes.Extrude001.material}
						/>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.top_tube_2.geometry}
							material={gltf.nodes.top_tube_2.material}
							position={[46.59, 0, -69.35]}
							rotation={[Math.PI, -0.2, Math.PI]}
						/>
					</T.Group>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.top_lugg_1.geometry}
						material={gltf.nodes.top_lugg_1.material}
						position={[3.97, -5.74, 1.52]}
						rotation={[0, 1.57, 0]}
					/>
				</T.Group>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.down_tube_1.geometry}
					material={gltf.nodes.down_tube_1.material}
					position={[-0.25, -1.91, 3.6]}
					rotation={[-Math.PI, 0.76, -Math.PI]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.top_tube_1.geometry}
					material={gltf.nodes.top_tube_1.material}
					position={[3.67, -1.91, 3.43]}
					rotation={[Math.PI, -0.2, Math.PI]}
				/>
			</T.Group>
			<T.Group position={[13.94, 3.72, 25.62]} rotation={[0.98, 1.41, -0.96]}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.bottom_bracket_2.geometry}
					material={gltf.nodes.bottom_bracket_2.material}
					position={[-2.08, -5.83, -15.92]}
					rotation={[1.44, -0.01, 1.48]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.down_tube.geometry}
					material={gltf.nodes.down_tube.material}
					position={[23.44, -3.52, 3.01]}
					rotation={[-0.12, 0.9, -0.01]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Extrude_4.geometry}
					material={gltf.nodes.Extrude_4.material}
					position={[34.27, -9.74, -42.43]}
					rotation={[3.12, -1.15, -1.52]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.seat_tube.geometry}
					material={gltf.nodes.seat_tube.material}
					position={[25.05, -7.42, -26.48]}
					rotation={[-0.15, -1.17, -0.02]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.stem.geometry}
					material={gltf.nodes.stem.material}
					position={[49.01, -1.42, 20.4]}
					rotation={[2.99, 1.28, -3.12]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.top_tube.geometry}
					material={gltf.nodes.top_tube.material}
					position={[49.54, -5.1, -7.51]}
					rotation={[-0.13, 0.09, -0.01]}
				/>
			</T.Group>
			<T.Group position={[6.8, 0, 32.62]} rotation={[0, 0.02, Math.PI / 2]}>
				<T.Group position={[0.09, -46.65, -8.14]} rotation={[-Math.PI / 2, 0, 0]}>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Front_Wheel_Lock.geometry}
						material={gltf.nodes.Front_Wheel_Lock.material}
						position={[0.18, 0.63, 1.12]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Tire_Front.geometry}
						material={gltf.nodes.Tire_Front.material}
						position={[-0.09, -0.31, -0.56]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Wheel_Front.geometry}
						material={gltf.nodes.Wheel_Front.material}
						position={[-0.09, -0.31, -0.56]}
					/>
				</T.Group>
				<T.Group position={[0, 0, -26.78]} rotation={[-Math.PI / 2, 0, 0]}>
					<T.Group position={[0, 28.86, -45.64]} rotation={[-0.11, 0, 0]}>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.Gear_Switch.geometry}
							material={gltf.nodes.Gear_Switch.material}
							position={[0, 3.11, -5.76]}
						/>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.Steer.geometry}
							material={gltf.nodes.Steer.material}
							position={[0, -3.11, 5.76]}
						/>
					</T.Group>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Chain.geometry}
						material={gltf.nodes.Chain.material}
						position={[5.04, -24.16, 26.06]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Cogset.geometry}
						material={gltf.nodes.Cogset.material}
						position={[4.09, -16.54, 51.27]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Main_Gear.geometry}
						material={gltf.nodes.Main_Gear.material}
						position={[0, -24.2, 9.23]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Pedal_Left.geometry}
						material={gltf.nodes.Pedal_Left.material}
						position={[-10.03, -7.45, 9.23]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Pedal_Right.geometry}
						material={gltf.nodes.Pedal_Right.material}
						position={[10.03, -40.94, 9.23]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Rear_Derailleur.geometry}
						material={gltf.nodes.Rear_Derailleur.material}
						position={[6.54, -25.18, 51.92]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Rear_Wheel_Lock.geometry}
						material={gltf.nodes.Rear_Wheel_Lock.material}
						position={[0.24, -18.12, 52.33]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Small_Star_1.geometry}
						material={gltf.nodes.Small_Star_1.material}
						position={[5, -24.99, 49.19]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Small_Star_2.geometry}
						material={gltf.nodes.Small_Star_2.material}
						position={[5, -30.58, 51.47]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Tire_Rear.geometry}
						material={gltf.nodes.Tire_Rear.material}
						position={[0, -16.56, 51.27]}
					/>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Wheel_Rear.geometry}
						material={gltf.nodes.Wheel_Rear.material}
						position={[0, -16.56, 51.27]}
					/>
				</T.Group>
				<T.Group position={[-0.11, 23.22, -49.4]} rotation={[-1.54, 0, 0]}>
					<T.Group position={[-0.01, 9.59, 8.02]}>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.Seat_Lock.geometry}
							material={gltf.nodes.Seat_Lock.material}
							position={[-0.09, 5.23, 6.88]}
							rotation={[-0.02, 0, 0]}
						/>
					</T.Group>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.Seat.geometry}
						material={gltf.nodes.Seat.material}
						position={[0.1, 11.24, 4.81]}
						rotation={[-0.02, 0, 0]}
					/>
				</T.Group>
			</T.Group>
			<T.Group position={[13.94, 3.72, 25.62]} rotation={[0.98, 1.41, -0.96]}>
				<T.Group position={[-2.1, -8, -14.91]} rotation={[-0.69, -1.56, -0.56]}>
					<T.Group position={[-16.91, -0.42, -37.18]} rotation={[0, 0, -0.02]}>
						<T.Group position={[-26.01, -3.98, 33.06]}>
							<T.Mesh
								castShadow
								receiveShadow
								geometry={gltf.nodes.Cylinder001.geometry}
								material={gltf.nodes.Cylinder001.material}
								position={[-0.23, 0.9, -0.1]}
								rotation={[Math.PI / 2, 0, 0]}
							/>
							<T.Mesh
								castShadow
								receiveShadow
								geometry={gltf.nodes.Extrude_2001.geometry}
								material={gltf.nodes.Extrude_2001.material}
								position={[-0.71, -0.2, 0.33]}
							/>
						</T.Group>
						<T.Group position={[-1.09, -1.54, 12.1]}>
							<T.Mesh
								castShadow
								receiveShadow
								geometry={gltf.nodes.rear_wheel_lug.geometry}
								material={gltf.nodes.rear_wheel_lug.material}
								position={[-15.93, -2.07, 24.2]}
							/>
						</T.Group>
						<T.Group position={[10.89, 2.69, 36.59]}>
							<T.Mesh
								castShadow
								receiveShadow
								geometry={gltf.nodes.Cube_1_3.geometry}
								material={gltf.nodes.Cube_1_3.material}
								position={[-2.99, -3.32, -0.58]}
								rotation={[0, -0.09, -0.12]}
							/>
						</T.Group>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.lug_2.geometry}
							material={gltf.nodes.lug_2.material}
							position={[12.39, 7.61, 34.69]}
							rotation={[0.89, 1.43, -0.88]}
						/>
					</T.Group>
					<T.Group position={[-5.8, 2.28, 17.78]} rotation={[0, 0.08, 0]}>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.R_upper_fork_1.geometry}
							material={gltf.nodes.R_upper_fork_1.material}
							position={[-9.3, -1.23, -66.25]}
							rotation={[2.86, 0.55, -2.97]}
						/>
					</T.Group>
					<T.Group position={[-16.91, 4.95, -37.18]} rotation={[0, 0, 0.02]}>
						<T.Group position={[-1.09, 1.54, 12.1]}>
							<T.Group position={[-24.92, 2.58, 20.96]}>
								<T.Mesh
									castShadow
									receiveShadow
									geometry={gltf.nodes.Cylinder_2001.geometry}
									material={gltf.nodes.Cylinder_2001.material}
									position={[-0.23, -0.9, -0.1]}
									rotation={[Math.PI / 2, 0, 0]}
								/>
								<T.Mesh
									castShadow
									receiveShadow
									geometry={gltf.nodes.Extrude_3.geometry}
									material={gltf.nodes.Extrude_3.material}
									position={[-0.71, 0.34, 0.33]}
								/>
							</T.Group>
							<T.Mesh
								castShadow
								receiveShadow
								geometry={gltf.nodes.rear_wheel_lug_2.geometry}
								material={gltf.nodes.rear_wheel_lug_2.material}
								position={[-15.93, 2.07, 24.2]}
							/>
						</T.Group>
						<T.Group position={[10.37, -2.67, 54.47]}>
							<T.Mesh
								castShadow
								receiveShadow
								geometry={gltf.nodes.Cube_1_4.geometry}
								material={gltf.nodes.Cube_1_4.material}
								position={[-2.47, 3.32, -18.46]}
								rotation={[0, -0.09, -0.12]}
							/>
						</T.Group>
						<T.Mesh
							castShadow
							receiveShadow
							geometry={gltf.nodes.lug_2_1.geometry}
							material={gltf.nodes.lug_2_1.material}
							position={[12.34, -7.59, 34.67]}
							rotation={[1.03, 1.4, -1.02]}
						/>
					</T.Group>
					<T.Mesh
						castShadow
						receiveShadow
						geometry={gltf.nodes.R_upper_fork.geometry}
						material={gltf.nodes.R_upper_fork.material}
						position={[-20.29, 3.51, -47.53]}
						rotation={[2.88, 0.47, -3]}
					/>
				</T.Group>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.bottom_bracket.geometry}
					material={gltf.nodes.bottom_bracket.material}
					position={[-2.08, -5.83, -15.92]}
					rotation={[1.44, -0.01, 1.48]}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Tube_2.geometry}
					material={gltf.nodes.Tube_2.material}
					position={[-1.72, -6.52, -21.09]}
					rotation={[1.44, -0.01, 1.48]}
				/>
			</T.Group>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.bearing.geometry}
				material={gltf.nodes.bearing.material}
				position={[39.71, 0, -14.66]}
				rotation={[0, 0.24, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.bearing_1.geometry}
				material={gltf.nodes.bearing_1.material}
				position={[36.69, 0, -29.07]}
				rotation={[0, 0.21, 0]}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
