<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 bicycle.glb
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/bicycle.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes['axle-nut-2_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut-3_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut-4_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut-5_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut-6_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut-7_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut-8_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['axle-nut_Cylinder022'].geometry}
      material={gltf.materials['axle-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['bar-end-plugs_Circle002'].geometry}
      material={gltf.materials['end-plugs']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['bottle-cage-nut-1_Cylinder010'].geometry}
      material={gltf.materials['bottlecage-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['bottle-cage-nut-2_Cylinder010'].geometry}
      material={gltf.materials['bottlecage-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['bottle-cage-nut-3_Cylinder010'].geometry}
      material={gltf.materials['bottlecage-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['bottle-cage-nut-4_Cylinder010'].geometry}
      material={gltf.materials['bottlecage-nuts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.bullhorn_Cylinder.geometry}
      material={gltf.materials.bullhorn}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes['chain-inner-link_Circle_1'].geometry}
        material={gltf.materials['chain-inner-links']}
      />
      <T.Mesh
        geometry={gltf.nodes['chain-inner-link_Circle_2'].geometry}
        material={gltf.materials['chain-pins']}
      />
    </T.Group>
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes['chain-outer-link_Circle002_1'].geometry}
        material={gltf.materials['chain-outer-links']}
      />
      <T.Mesh
        geometry={gltf.nodes['chain-outer-link_Circle002_2'].geometry}
        material={gltf.materials['chain-pins']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes['chainring-black_Circle005'].geometry}
      material={gltf.materials['chainrnig-black']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle000_Circle006.geometry}
      material={gltf.materials['chainring-metal']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle002_Circle003.geometry}
      material={gltf.materials['cog-lockring']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle003_Circle012.geometry}
      material={gltf.materials['reflector-orange-plastic']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle003_Mesh001.geometry}
      material={gltf.materials['grand-bois-tire']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle004.geometry}
      material={gltf.materials['chainring-metal_NONE']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle004_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle005_Circle008.geometry}
      material={gltf.materials['pedal-axle']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle005_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle006_Circle001.geometry}
      material={gltf.materials.pedal}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle006_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle008_Circle013.geometry}
      material={gltf.materials['pedal-reflector']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle008_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle009_Circle013.geometry}
      material={gltf.materials['pedal-reflector']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle009_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle010_Circle012.geometry}
      material={gltf.materials['reflector-orange-plastic']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle010_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle011_Circle015.geometry}
      material={gltf.materials['pedal-bolt']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle011_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle012_Circle001.geometry}
      material={gltf.materials.pedal}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle012_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle013_Circle015.geometry}
      material={gltf.materials['pedal-bolt']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle013_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle014_Circle012.geometry}
      material={gltf.materials['reflector-orange-plastic']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle014_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle015_Circle013.geometry}
      material={gltf.materials['pedal-reflector']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle015_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle016_Circle013.geometry}
      material={gltf.materials['pedal-reflector']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle016_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle017_Circle012.geometry}
      material={gltf.materials['reflector-orange-plastic']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle017_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle018_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle018_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle019_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle019_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle020_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle020_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle021_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle021_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle022_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle022_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle023_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle023_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle024_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle024_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle025_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle025_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle026_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle026_Mesh006.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle027_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle027_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle028_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle028_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle029_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle029_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle030_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle030_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle031_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle031_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle032_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle032_Mesh002.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle033_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle033_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle034_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle034_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle035_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle035_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle036_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle036_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle037_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle037_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle038_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle038_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle039_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle039_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle040_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle040_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle041_Circle017.geometry}
      material={gltf.materials['pedal-spikes']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle041_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle042_Circle008.geometry}
      material={gltf.materials['pedal-axle']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle042_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle043_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle044_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle045_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle046_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle047_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle048_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle049_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle050_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle051_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle052_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle053_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle054_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle055_Mesh001.geometry}
      material={gltf.materials['grand-bois-tire']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle056_Mesh.geometry}
      material={gltf.materials.rims}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle057_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle058_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle059_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle060_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle061_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle062_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle063_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle064_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle065_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle066_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle067_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle068_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle069_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle070_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle071_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle072_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle073_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle074_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle075_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle076_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle077_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle078_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle079_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle080_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle081_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle082_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle083_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle084_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle085_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle086_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle087_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle088_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle089_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle090_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle091_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle092_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle093_Mesh003.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle094_Mesh005.geometry}
      material={gltf.materials.spoke}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle_Mesh.geometry}
      material={gltf.materials.rims}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.cog_Cylinder002.geometry}
      material={gltf.materials.cog}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.collar_Cylinder001.geometry}
      material={gltf.materials['bb-collar']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.crankset_Plane.geometry}
      material={gltf.materials.crankset}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials['hub-inner-ring']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder004.geometry}
      material={gltf.materials['hub-bearing']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder006_Cylinder007.geometry}
      material={gltf.materials['hub-bearing']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder007_Cylinder008.geometry}
      material={gltf.materials['hub-inner-ring']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder_Cylinder003.geometry}
      material={gltf.materials['chainring-metal_NONE']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-1_Cylinder006'].geometry}
      material={gltf.materials['crankset-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-2_Cylinder006'].geometry}
      material={gltf.materials['crankset-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-3_Cylinder004'].geometry}
      material={gltf.materials['chainring-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-4_Cylinder004'].geometry}
      material={gltf.materials['chainring-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-5_Cylinder004'].geometry}
      material={gltf.materials['chainring-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-6_Cylinder004'].geometry}
      material={gltf.materials['chainring-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['drivetrain-bolt-7_Cylinder004'].geometry}
      material={gltf.materials['chainring-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.fork_Circle004.geometry}
      material={gltf.materials['wabi-frame-carpaint']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.frame_Cylinder_1.geometry}
        material={gltf.materials['wabi-frame-mix']}
      />
      <T.Mesh
        geometry={gltf.nodes.frame_Cylinder_2.geometry}
        material={gltf.materials['wabi-frame-mix_NONE']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes['front-axle_Cylinder031'].geometry}
      material={gltf.materials.axles}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes['front-hub_Cylinder001_1'].geometry}
        material={gltf.materials.hubs}
      />
      <T.Mesh
        geometry={gltf.nodes['front-hub_Cylinder001_2'].geometry}
        material={gltf.materials.hubs_NONE}
      />
    </T.Group>
    <T.Group rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.headset_Cylinder041_1.geometry}
        material={gltf.materials.headset}
      />
      <T.Mesh
        geometry={gltf.nodes.headset_Cylinder041_2.geometry}
        material={gltf.materials.headset_NONE}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Helix003_Mesh011.geometry}
      material={gltf.materials.bartape}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Helix_Mesh004.geometry}
      material={gltf.materials.hubs_NONE}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['lock-nut-2_Cylinder030'].geometry}
      material={gltf.materials['lock-nut']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['lock-nut-3_Cylinder030'].geometry}
      material={gltf.materials['lock-nut']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['lock-nut-4_Cylinder030'].geometry}
      material={gltf.materials['lock-nut']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['lock-nut_Cylinder030'].geometry}
      material={gltf.materials['lock-nut']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials['crankset_andel-crankset-normalmap.png']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['rear-axle_Cylinder028'].geometry}
      material={gltf.materials.axles}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['rear-hub_Cylinder'].geometry}
      material={gltf.materials.hubs}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['saddle-black-plastic_Plane003'].geometry}
      material={gltf.materials['saddle-black-plastic']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['saddle-clamp-bolt-glossy_Cylinder001'].geometry}
      material={gltf.materials['saddle-clamp-bolt-glossy']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['saddle-clamp-bolt_Cylinder'].geometry}
      material={gltf.materials['saddle-clamp-bolt']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['saddle-rails_Mesh'].geometry}
      material={gltf.materials['saddle-rails']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['saddle-velo-vl-1311_Plane001'].geometry}
      material={gltf.materials.saddle}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['seat-clamp_Circle'].geometry}
      material={gltf.materials['seat-clamp']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['seat-post'].geometry}
      material={gltf.materials['seat-post']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['seat-post-clamp-bolt_Circle012'].geometry}
      material={gltf.materials['seat-post-clamp-bolt']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['seat-post-clamp-nut_Circle011'].geometry}
      material={gltf.materials['seat-post-clamp-nut']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['seat-post-clamp_Circle009'].geometry}
      material={gltf.materials['seat-post-clamp']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['sidewall-front_Mesh007'].geometry}
      material={gltf.materials.sidewalls}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['sidewall-rear_Mesh007'].geometry}
      material={gltf.materials.sidewalls}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.spacers_Cylinder000.geometry}
      material={gltf.materials.spacers}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-1_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-2_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-3_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-4_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-5_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-6_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-bolt-7_Cylinder006'].geometry}
      material={gltf.materials['stem-bolts']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['stem-cap_Cylinder007'].geometry}
      material={gltf.materials['stem-cap']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.stem_Sphere.geometry}
      material={gltf.materials.stem}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['valve-cap001_Circle'].geometry}
      material={gltf.materials['valve-cap']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes['valve-cap_Circle'].geometry}
      material={gltf.materials['valve-cap']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.valve001_Mesh008.geometry}
      material={gltf.materials.valve}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.valve_Mesh008.geometry}
      material={gltf.materials.valve}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.washer_Cylinder000.geometry}
      material={gltf.materials.washer}
      rotation={[Math.PI / 2, 0, 0]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
