<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/mercian-models/lugged-logo-poll-2.glb --draco
-->

<script>
	import { partColours } from '$lib/PartColours.svelte';
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { DoubleSide } from 'three';
	import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = new DRACOLoader();
	dracoLoader.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');

	const gltf = useGltf('/mercian-models/lugged-logo-poll-2.glb', { dracoLoader: dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props} position={[-0.2, 0.1, 1.55]}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.mercian_logo.geometry} material={gltf.materials.Mat}>
			<T.MeshStandardMaterial color={partColours.logo} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube006.geometry} material={gltf.nodes.Cube006.material}>
			<T.MeshStandardMaterial color={partColours.logo} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.bearing.geometry} material={gltf.nodes.bearing.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.bearing1.geometry} material={gltf.nodes.bearing1.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Tube.geometry} material={gltf.nodes.Tube.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube1.geometry} material={gltf.nodes.Cube1.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.nodes.Cube.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube002.geometry} material={gltf.nodes.Cube002.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube003.geometry} material={gltf.nodes.Cube003.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.down_tube1.geometry} material={gltf.nodes.down_tube1.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.top_tube1.geometry} material={gltf.nodes.top_tube1.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Lug_1.geometry} material={gltf.nodes.Lug_1.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Lug_11.geometry} material={gltf.nodes.Lug_11.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Lug_12.geometry} material={gltf.nodes.Lug_12.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Lug_13.geometry} material={gltf.nodes.Lug_13.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.top_lugg_1.geometry} material={gltf.nodes.top_lugg_1.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Extrude.geometry} material={gltf.nodes.Extrude.material}>
			<T.MeshStandardMaterial color={partColours.forks} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.top_tube2.geometry} material={gltf.nodes.top_tube2.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.bottom_bracket001.geometry}
			material={gltf.nodes.bottom_bracket001.material}
		/>
		<T.Mesh geometry={gltf.nodes.down_tube002.geometry} material={gltf.nodes.down_tube002.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Extrude003.geometry} material={gltf.materials['Material.001']}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.seat_tube.geometry}>
			<T.MeshStandardMaterial
				color={partColours.frame}
				side={DoubleSide}
				roughness={0.036491}
				metalness={0.346457}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.stem.geometry} material={gltf.nodes.stem.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.top_tube.geometry} material={gltf.nodes.top_tube.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.bottom_bracket.geometry}
			material={gltf.nodes.bottom_bracket.material}
		>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Tube001.geometry} material={gltf.nodes.Tube001.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.R_upper_fork.geometry} material={gltf.nodes.R_upper_fork.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.lug_2.geometry} material={gltf.nodes.lug_2.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cylinder.geometry} material={gltf.nodes.Cylinder.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Extrude001.geometry} material={gltf.nodes.Extrude001.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.rear_wheel_lug.geometry}
			material={gltf.nodes.rear_wheel_lug.material}
		>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube004.geometry} material={gltf.nodes.Cube004.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.R_upper_fork1.geometry}
			material={gltf.nodes.R_upper_fork1.material}
		>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.lug_21.geometry} material={gltf.nodes.lug_21.material}>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.rear_wheel_lug001.geometry}
			material={gltf.nodes.rear_wheel_lug001.material}
		>
			<T.MeshStandardMaterial color={partColours.lugs} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cylinder001.geometry} material={gltf.nodes.Cylinder001.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Extrude002.geometry} material={gltf.nodes.Extrude002.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube005.geometry} material={gltf.nodes.Cube005.material}>
			<T.MeshStandardMaterial color={partColours.frame} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Front_Wheel_Lock.geometry}>
			<T.MeshStandardMaterial color={partColours.axel} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Tire_Front.geometry} material={gltf.materials['Material.004']}>
			<T.MeshStandardMaterial color={partColours.tire} roughness={1} metalness={0.2} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Wheel_Front.geometry} material={gltf.materials['Material.005']} />
		<T.Mesh geometry={gltf.nodes.Chain.geometry} material={gltf.materials['Material.012']} />
		<T.Mesh geometry={gltf.nodes.Cogset.geometry} material={gltf.materials['Material.017']} />
		<T.Mesh geometry={gltf.nodes.Main_Gear.geometry} material={gltf.materials['Material.009']} />
		<T.Mesh geometry={gltf.nodes.Pedal_Left.geometry} material={gltf.materials['Material.010']} />
		<T.Mesh geometry={gltf.nodes.Pedal_Right.geometry} material={gltf.materials['Material.011']} />
		<T.Mesh
			geometry={gltf.nodes.Rear_Derailleur.geometry}
			material={gltf.materials['Material.013']}
		/>
		<T.Mesh
			geometry={gltf.nodes.Rear_Wheel_Lock.geometry}
			material={gltf.materials['Material.016']}
		/>
		<T.Mesh geometry={gltf.nodes.Small_Star_1.geometry} material={gltf.materials['Material.015']} />
		<T.Mesh geometry={gltf.nodes.Small_Star_2.geometry} material={gltf.materials['Material.018']} />
		<T.Mesh geometry={gltf.nodes.Tire_Rear.geometry} material={gltf.materials['Material.014']}>
			<T.MeshStandardMaterial color={partColours.tire} roughness={1} metalness={0.2} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Wheel_Rear.geometry} material={gltf.materials['Material.019']} />
		<T.Mesh geometry={gltf.nodes.Gear_Switch.geometry} material={gltf.materials['Material.007']} />
		<T.Mesh geometry={gltf.nodes.Steer.geometry} material={gltf.materials['Material.008']} />
		<T.Mesh geometry={gltf.nodes.Seat.geometry} material={gltf.materials['Material.003']} />
		<T.Mesh geometry={gltf.nodes.Seat_Lock.geometry} material={gltf.materials['Material.002']} />
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
