<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/mercian-models/lugless-all-logos-2.glb
-->

<script>
	import { partColours } from '$lib/PartColours.svelte';
	import { T } from '@threlte/core';
	import * as THREE from 'three';
	import { useGltf, useTexture } from '@threlte/extras';
	import { BackSide, DoubleSide } from 'three';
	import { FlakesTexture } from 'three/examples/jsm/Addons.js';
	import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
	import { onMount } from 'svelte';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = new DRACOLoader();
	dracoLoader.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');

	const gltf = useGltf('/mercian-models/lugless-all-logos-2.glb', {
		dracoLoader: dracoLoader
	});

	const flakesCanvas = new FlakesTexture();
	const normalMap3 = new THREE.CanvasTexture(flakesCanvas);
	// Configure the texture
	normalMap3.wrapS = THREE.RepeatWrapping;
	normalMap3.wrapT = THREE.RepeatWrapping;
	normalMap3.repeat.set(10, 6);
	normalMap3.anisotropy = 16;
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Mercian_Logo.geometry} material={gltf.nodes.Mercian_Logo.material}>
			<T.MeshPhysicalMaterial
				color={partColours.logo}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Mercian_Logo_Keyline.geometry}
			material={gltf.nodes.Mercian_Logo_Keyline.material}
		>
			<T.MeshPhysicalMaterial
				color={partColours.logoKeyline}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={DoubleSide}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Pole_Keyline_1.geometry} material={gltf.materials['Material.001']}>
			<T.MeshPhysicalMaterial
				color={partColours.poleKeyline}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Pole.geometry} material={gltf.materials.Material}>
			<T.MeshPhysicalMaterial
				color={partColours.pole}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Pole_Keyline_2.geometry} material={gltf.materials['Material.003']}>
			<T.MeshPhysicalMaterial
				color={partColours.poleKeyline}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Mercian_Logo_Flip.geometry}
			material={gltf.nodes.Mercian_Logo_Flip.material}
		>
			<T.MeshPhysicalMaterial
				color={partColours.logo}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Mercian_Logo_Keyline_Flip.geometry}
			material={gltf.nodes.Mercian_Logo_Keyline_Flip.material}
		>
			<T.MeshPhysicalMaterial
				color={partColours.logoKeyline}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={DoubleSide}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Keyline_Dupe.geometry} material={gltf.materials['Material.005']}>
			<T.MeshPhysicalMaterial
				color={partColours.frontLogoKeyline}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.M_Dupe.geometry} material={gltf.materials['Material.006']}>
			<T.MeshPhysicalMaterial
				color={partColours.frontLogo}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.bearing.geometry}
			material={gltf.nodes.bearing.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				specularColor="#000000"
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.bearing_2.geometry}
			material={gltf.nodes.bearing_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				specularColor="#000000"
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Extrude_3.geometry}
			material={gltf.nodes.Extrude_3.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.frame_2.geometry}
			material={gltf.nodes.frame_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.nodes.Cube.material} castShadow>
			<T.MeshPhysicalMaterial
				color={partColours.forks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Cube_1_3.geometry}
			material={gltf.nodes.Cube_1_3.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.forks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.bottom_bracket.geometry}
			material={gltf.nodes.bottom_bracket.material}
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Tube.geometry} material={gltf.nodes.Tube.material} castShadow>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Lug_1.geometry} material={gltf.nodes.Lug_1.material} castShadow>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Lug_1_1.geometry}
			material={gltf.nodes.Lug_1_1.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.R_upper_fork.geometry}
			material={gltf.nodes.R_upper_fork.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.R_upper_fork_2.geometry}
			material={gltf.nodes.R_upper_fork_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.lug_2.geometry} material={gltf.nodes.lug_2.material} castShadow>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Cylinder.geometry}
			material={gltf.nodes.Cylinder.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Extrude.geometry}
			material={gltf.nodes.Extrude.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.rear_wheel_lug.geometry}
			material={gltf.nodes.rear_wheel_lug.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Cube_1.geometry} material={gltf.nodes.Cube_1.material} castShadow>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
				side={BackSide}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.lug_2_1.geometry}
			material={gltf.nodes.lug_2_1.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.rear_wheel_lug_2.geometry}
			material={gltf.nodes.rear_wheel_lug_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Cylinder_2.geometry}
			material={gltf.nodes.Cylinder_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Extrude_2.geometry}
			material={gltf.nodes.Extrude_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Cube_1_2.geometry}
			material={gltf.nodes.Cube_1_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.rearForks}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Chain.geometry} material={gltf.nodes.Chain.material} />
		<T.Mesh geometry={gltf.nodes.Cogset.geometry} material={gltf.nodes.Cogset.material} />
		<T.Mesh
			geometry={gltf.nodes.Frame_Details.geometry}
			material={gltf.nodes.Frame_Details.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Frame_Details_2.geometry}
			material={gltf.nodes.Frame_Details_2.material}
			castShadow
		>
			<T.MeshPhysicalMaterial
				color={partColours.frame}
				roughness={0.5}
				metalness={0.9}
				clearcoat={1}
				normalMap={normalMap3}
				normalScale={[0.15, 0.15]}
				clearcoatRoughness={0.1}
			/>
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Main_Gear.geometry}
			material={gltf.nodes.Main_Gear.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Pedal_Left.geometry}
			material={gltf.nodes.Pedal_Left.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Pedal_Right.geometry}
			material={gltf.nodes.Pedal_Right.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Rear_Derailleur.geometry}
			material={gltf.nodes.Rear_Derailleur.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Rear_Wheel_Lock.geometry}
			material={gltf.nodes.Rear_Wheel_Lock.material}
		>
			<T.MeshStandardMaterial color={partColours.axel} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Small_Star_1.geometry}
			material={gltf.nodes.Small_Star_1.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Small_Star_2.geometry}
			material={gltf.nodes.Small_Star_2.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Tire_Rear.geometry}
			material={gltf.nodes.Tire_Rear.material}
			castShadow
		>
			<T.MeshStandardMaterial color={partColours.tire} roughness={1} metalness={0.2} />
		</T.Mesh>
		<T.Mesh geometry={gltf.nodes.Wheel_Rear.geometry} material={gltf.nodes.Wheel_Rear.material} />
		<T.Mesh
			geometry={gltf.nodes.Front_Wheel_Lock.geometry}
			material={gltf.nodes.Front_Wheel_Lock.material}
			castShadow
		>
			<T.MeshStandardMaterial color={partColours.axel} roughness={0.036491} metalness={0.346457} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Tire_Front.geometry}
			material={gltf.nodes.Tire_Front.material}
			castShadow
		>
			<T.MeshStandardMaterial color={partColours.tire} roughness={1} metalness={0.2} />
		</T.Mesh>
		<T.Mesh
			geometry={gltf.nodes.Wheel_Front.geometry}
			material={gltf.nodes.Wheel_Front.material}
			castShadow
		/>
		<T.Mesh
			geometry={gltf.nodes.Gear_Switch.geometry}
			material={gltf.nodes.Gear_Switch.material}
			castShadow
		/>
		<T.Mesh geometry={gltf.nodes.Steer.geometry} material={gltf.nodes.Steer.material} castShadow />
		<T.Mesh geometry={gltf.nodes.Seat.geometry} material={gltf.nodes.Seat.material} castShadow />
		<T.Mesh
			geometry={gltf.nodes.Seat_Lock.geometry}
			material={gltf.nodes.Seat_Lock.material}
			castShadow
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
